# hugo server --themesDir ...

baseURL: https://qiongshao.jmadeinapril.com
title: 穹顶的少年
theme: hugo-book

# language setting
defaultContentLanguage: zh
defaultContentLanguageInSubdir: true

PygmentsCodeFences: true
enableGitInfo: true

languages:
  zh:
    languageCode: zh
    languageName: 中文
    contentDir: content/zh
    weight: 1

  # en:
  #   languageCode: en-US
  #   languageName: English
  #   contentDir: content/en
  #   weight: 2

# Book configuration
disablePathToLower: true

params:
  Description: 穹顶的少年（一）丹青画卷

  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme: "auto"

  # show or hide table of contents for page
  BookShowToC: false

  # Set bundle to render side menu
  # if not specified file structure and weights will be used
  BookMenuBundle: /menu

  # specify section of content to render as menu
  # if bookMenuBundle is not set, 'docs' is value by default
  BookSection: docs

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable.
  BookEditURL: https://github.com/pseudoyu/jmadeinapril-book-qiongshao/edit/master/content/zh/

    # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat: "January 2, 2006"