# hugo server --themesDir ...

baseURL: https://qiongshao.jmadeinapril.com
title: 穹顶的少年
theme: hugo-book

# language setting
defaultContentLanguage: zh
defaultContentLanguageInSubdir: true

PygmentsCodeFences: true

languages:
  zh:
    languageCode: zh
    languageName: 中文
    contentDir: content/zh
    weight: 1

  # en:
  #   languageCode: en-US
  #   languageName: English
  #   contentDir: content/en
  #   weight: 2

# Book configuration
disablePathToLower: true

params:
  Description: 穹顶的少年（一）丹青画卷

  # show or hide table of contents for page
  BookShowToC: true

  # Set bundle to render side menu
  # if not specified file structure and weights will be used
  BookMenuBundle: /menu

  # specify section of content to render as menu
  # if bookMenuBundle is not set, 'docs' is value by default
  BookSection: docs

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable.
  BookEditURL: https://github.com/pseudoyu/jmadeinapril-book-qiongshao/edit/master/content/zh/